//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyboardEPCS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyboardEPCS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Project Gutenberg EBook of Adventures of Huckleberry Finn, Complete
        ///by Mark Twain (Samuel Clemens)
        ///
        ///This eBook is for the use of anyone anywhere at no cost and with
        ///almost no restrictions whatsoever.  You may copy it, give it away or
        ///re-use it under the terms of the Project Gutenberg License included
        ///with this eBook or online at www.gutenberg.net
        ///
        ///
        ///Title: Adventures of Huckleberry Finn, Complete
        ///
        ///Author: Mark Twain (Samuel Clemens)
        ///
        ///Release Date: August 20, 2006 [EBook #76]
        ///[This file last [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string huckleberryfin {
            get {
                return ResourceManager.GetString("huckleberryfin", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap keyboard_blank {
            get {
                object obj = ResourceManager.GetObject("keyboard_blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Keyboard3 {
            get {
                object obj = ResourceManager.GetObject("Keyboard3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1043{\fonttbl{\f0\fswiss\fcharset0 Arial;}{\f1\fswiss\fprq2\fcharset0 Arial;}}
        ///{\*\generator Msftedit 5.41.21.2506;}\viewkind4\uc1\pard\b\f0\fs20 Usage:\b0\par
        ///\par
        ///Press the start button to start with the current settings. Press start with random to use the current settings except for the set keyboard, which is replaced by a random keyboard. Resume from.. can resume an ealier saved running algorithm. While running the alg. can be stopped, paused/resumed and saved. Th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mainFormDoc {
            get {
                return ResourceManager.GetString("mainFormDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1043{\fonttbl{\f0\fswiss\fcharset0 Arial;}}
        ///{\*\generator Msftedit 5.41.21.2506;}\viewkind4\uc1\pard\b\f0\fs20 Usage:\b0\par
        ///\par
        ///The three boxes on the left show the corpi (corpuses), keyboards (called permutations) and typestyles you have stored. You can select one and delete it with the corresponding remove button. The small boxes allow you to type in a name for creating a new corpus or typestyle. A new keyboard is made in a seperate menu, which can be accessed by  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string settingFormDoc {
            get {
                return ResourceManager.GetString("settingFormDoc", resourceCulture);
            }
        }
    }
}
